---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signed-commit-check
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: signed-commit-check
    spec:
      containers:
      - name: signed-commit-check
        image: quay.io/ukhomeofficedigital/signed-commit-check:{{.VERSION}}
        securityContext:
          runAsNonRoot: true
        ports:
          - name: http
            containerPort: 4000
        env:
          - name: GITHUB_PRIVATEKEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: GITHUB_PRIVATEKEY
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
