---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: signed-commit-ingress
spec:
  ingressClassName: "nginx-external"
  rules:
  - host: signed-commit-check.{{ .DNS_ZONE }}
    http:
      paths:
      - backend:
          service:
            name: signed-commit-check-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific