---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: signed-commit-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
spec:
  rules:
  - host: signed-commit-check.{{ .DNS_ZONE }}
    http:
      paths:
      - backend:
          serviceName: signed-commit-check-service
          servicePort: 80
        path: /
